Paths: 
  data_raw_dir: "./data/raw/"
  image_raw_dir: "./data/raw/images/"
  image_train_path: "./data/raw/images/image_train/"
  X_train: "./data/raw/X_train.csv"
  y_train: "./data/raw/y_train.csv"
  TextOutlierReport: "./TextOutlierReport.txt"
  ImageDataFrameSavePath: "./data/tmp/"


